title: HTML Reference
subtitle: "Hướng dẫn miễn phí về HTML"
description: Hướng dẫn chi tiết về các thẻ trong HTML và thuộc tính đi kèm.
share: "HTML Reference: hướng dẫn chi tiết về các thẻ trong HTML và thuộc tính đi kèm."
url: http://localhost:4000
markdown: kramdown
permalink: pretty
exclude: ['node_modules']
